language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
      - rgoncalves@iobundle.com
      - jsousa@iobundle.com
    on_success: never
    on_failure: always
