language: rust

rust:
  - stable
  - beta

matrix:
  fast_finish: true
  include:
    - rust: nightly
      before_script:
        - rustup component add clippy-preview --toolchain=nightly
        - rustup component add rustfmt-preview --toolchain=nightly
      script:
        - cargo fmt -- --check
        - cargo clippy -- -D clippy

cache: cargo

notifications:
  email:
    recipients:
      - lfiolhais@iobundle.com
      - rgoncalves@iobundle.com
      - jsousa@iobundle.com
    on_success: never
    on_failure: always
