[package]
name = "adept_sim"
version = "0.1.0"
authors = ["Luís Fiolhais <lfiolhais@iobundle.com>", "Rafael Gonçalves <rgoncalves@iobundle.com>"]

[dependencies]
adapt-mem-adept = { path = "adapt-mem-adept" }
clap = "2.31.2"
